version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    extra_hosts:
      - "tower-arch:192.168.1.72"
    volumes:
      - ./volumes/config:/config
      - ./volumes/cache:/cache
      - /storage/library:/media/library:ro
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # environment:
      # - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
      # - "host.docker.internal:host-gateway"
