version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    networks:
      dockervlan1:
        ipv4_address: 192.168.1.88

networks:
  dockervlan1:
    name: dockervlan1
    driver: macvlan
    driver_opts:
      parent: guest
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          ip_range: "192.168.1.64/26"
          gateway: "192.168.1.1"
