version: '3.8'

services:
  portainer_agent:
    image: portainer/agent:2.18.4
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
