# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fb25c8c5-3a83-4b00-a8bb-266b25d84c84";
      fsType = "btrfs";
      options = [ "subvol=nisox-root,noatime,compress=zstd,discard" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fb25c8c5-3a83-4b00-a8bb-266b25d84c84";
      fsType = "btrfs";
      options = [ "subvol=nisox-home,noatime,compress=zstd,discard" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EF0A-E745";
      fsType = "vfat,noatime,discard";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
